site_name: PSQA Docs

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]

  

nav:
  - PSQA Docs: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - References: reference.md
  - Explanation: explanation.md  


